### ISSUE TITLE
Setup forms and validation using Formik and Yup

### ISSUE THREAD

**Issue by Gutto1** [eddb2-0/EDDB-2.0-frontend#24]
- Add Formik and Yup packages
- Create a new page with form validation example
- Add a link to the example page on the landing page

**Comment by aslink87** [comment]
[react-hook-form](https://react-hook-form.com/get-started) added instead of Formik
[zod](https://zod.dev/) added instead of Yup

Status:
1. '/commodities' page created and card added to the home page under the 'Trade' tab
2. form component created to pass commodity search object to back-end API

TODO:
1. styling pass on commodities page and child components
2. tests created to cover commodities page and children
3. validate form data with Zod
4. connect form submit data to POST call to API

**Comment by jbritain** [comment]
Can I call dibs on the styling pass..!

**Comment by Gutto1** [comment]
The implementation of the form is good to start, I'll just state a point so we can look in the future as I mentioned in discord.

- Inputs that are based on lists like commodities, bodies etc should have their own component that filter themselves.
  - For example: <CommoditiesSelect /> that recieves data from the BE and filters in the client (if it'll be the approach)
  
I don't know if we will do the client filtering or call BE for filters so it's just an idea. If we would call BE for filtering than making use of useEffect based on str.length would cause too much requests, we could move to dispatch the search string for when the user stops typing

**Comment by Gutto1** [comment]
I've added the following implementation:

- Added a component called `<CommoditiesField />`. It's an autocomplete that filters itself and has integation with the react-hook-form
- Updated the test file `form.test.tsx` so it can render the component properly with mocked up data

**Comment by aslink87** [comment]
- Add zod validation to form
- update form data to match API:
- example request:
`{
commodityId: "agronomic_treatment"
includeFleetCarriers: false
includeOdyssey: true
includePlanetary: false
maxLandingPadSize: "medium"
minDemand: 0
minSupply: 500000
referenceLocation: {
  xcoordinate: 0
  ycoordinate: 0
  zcoordinate: 0
}
}`

- until we establish the feature to request a system's coords from a separate endpoint i defaulted referenceLocation coords to '0'
