### ISSUE TITLE
Ensure the website base layout is compatible with different screen layouts - mobile, tablet, desktop

### ISSUE THREAD

**Issue by jbritain** [eddb2-0/EDDB-2.0-frontend#28]

**Comment by jbritain** [comment]
I have loaded up the website on my phone in both landscape and portrait and everything seems to be working well. Thought I would use the #20 branch while I was at it since no layout changes have been made on the dev branch since it was proposed.

![Screenshot_20230620-133956.png](https://github.com/ed-pilots-network/frontend/assets/50422789/2c454c7a-e2c1-4a4f-99f0-3ddcea3674f9)

![Screenshot_20230620-133946.png](https://github.com/ed-pilots-network/frontend/assets/50422789/5535575e-6e47-4fc4-9898-67a26c66fd4b)

Charging my terrible old tablet up at the moment to see how it looks on there but I imagine it will be fine.

**Comment by jbritain** [comment]
Other devices to consider checking compatibility on
- Nintendo 3DS
- Samsung Smart Fridge
- Android Wear
- Netscape Navigator

\j, of course

**Comment by nitishdhar** [comment]
We can close this issue and instead follow more like a continuous review process where any new layout / UI feature gets added, the PR should confirm if they tested this on different screen sizes. Would be great if there's some workflow we can add during commit that generates screenshots during playwright run on different (pre-defined) screens and developer can post those images in the PR

**Comment by westonnovelli** [comment]
Seems pretty easy to do something simple: https://playwright.dev/docs/screenshots

**Comment by aslink87** [comment]
> Seems pretty easy to do something simple: https://playwright.dev/docs/screenshots

This looks really cool weston. `await page.locator('.header').screenshot({ path: 'screenshot.png' });`
I'm curious if we can setup params for this before capturing the screenshot. Something that establishes a breakpoint or mimics a device then captures the image. Easy progression is to then post those images in Discord or in the PR. 

Looks like playwright has image comparisons: [test-snapshots](https://playwright.dev/docs/test-snapshots), but that seems like overkill.

Without that, the value added through just the screenshot function would be to automatically capture the images during testing so that they can be shared, vs manual screen-grabbing. If we can't do breakpoints, it may have little value.

**Comment by westonnovelli** [comment]
If you want me to take a deeper look at getting something set up, feel free to assign me to it. 👍

**Comment by nitishdhar** [comment]
Created an issue to track this ability for developers - https://github.com/ed-pilots-network/frontend/issues/39
