### ISSUE TITLE
Home Tabs Playwright tests fail intermittently

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#59]
Home Tabs Playwright tests fail intermittently

Keeping this open to get +1's if this keeps happening

**Comment by chrismou** [comment]
I get this on the actual dev site sometimes. I spin it up and the tabs are unresponsive. The page loader is spinning during this time as if the page hasn't finished loading.

When it happens it takes a few attempts at closing and reopening the browser tab and restarting the app before it works. So I wonder if this is actually an issue with the test, or the tabs themselves?

Though controversially, I'd question why we even need the tabs on the homepage. Can we just list all the options on one page?  I just don't get the value of it - we already have the nav menu, It feels like we've just added a second menu to the homepage. 

Right now I'm looking at a big 'ol pile of whitespace, and yet we're hiding core functionality behind clicks. Doesn't feel like great UX to me

![image](https://github.com/ed-pilots-network/frontend/assets/319883/b6286ff0-0bb4-48a8-ac33-493d91552f2d)

**Comment by aslink87** [comment]
That's a valid question for sure. We arrived here by kicking around the idea of guiding the user to places that suited the role they were presently using, whether trading, exploring, or refitting. You're right there's a lot of white space, especially in the outfit section.

Since we don't know all of the features we are going to offer, nor have we finished styling each of these grid components, perhaps we should wait for this discussion. I have a feeling the navbar will change quite a bit over time because it isn't really needed now unless on mobile.

The bug you're getting, is that on the hosted dev site or on your localhost env?

**Comment by nitishdhar** [comment]
The unintended background loading should get relaxed by this change - https://github.com/ed-pilots-network/frontend/pull/71. Some of it is due to pre-fetching link like /playground, which I have disabled now. About the UX, we will surely do some clean up once some features are finalized. The home page needs work, just not right now. Let's open an issue on UX separately.
